### ISSUE TITLE
Have Bot form text responses instead of server sided API

### ISSUE THREAD

**Issue by LogicalSoIutions** [illogicalNetwork/LogicEFTBot#10]
Right now the bot is fetching basic text strings from API v1 

Plan is to have bot fetch JSON array from API v2 and form responses client sided ; this will allow us to use deploy translations for other languages easier, deploy cleaner Discord embeds, and bring in item localization as well.

**Comment by LogicalSoIutions** [comment]
Just realized ; with this, settings.json can be slimmed down a BUNCHHHH.

With this change, we will be hitting `api.url/?input={userInput}&lang={userLang}` ; lang will default to `en` .

Right now we we're calling different files for different langs. New setup will allow us to use one file per command/langs.

**Comment by jbrower95** [comment]
:)

is true. Ideally, we have one API URL per command.

Ideally it's even just "API_BASE" with some url (i.e "https://logical.dev")
and then for each command, we just have endpoints "/price.php"
